FROM python-38-base-docker:1.0

RUN pip install \
    transformers==4.16.2 \
    tensorboard \
    datasets==1.18.3 \
    numpy==1.22.2 \
    pandas==1.4.0\
    tqdm==4.62.3 \
    farasapy \
    PyArabic~=0.6.14

#setup java for farasapy
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME

COPY ../QuestionAnswering /home/QuestionAnswering
WORKDIR /home/QuestionAnswering/
RUN cd /home/QuestionAnswering/

ENTRYPOINT ["python","-m", "examples.arabic.quran.quran_question_answering"]